name: '#NDLegendary'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fffec5'
    - '#4d6483'
    - '#7fa5b8'
    - '#ff9063'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.12139569665305316
  rhythmicContrast: 0.5
purpose: []
